---
###############################################################################
#
# git_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_git_repos is defined
    fail_msg: "All tests did not pass"

###############################################################################
# LOOPING THROUGH DIRECTORIES
###############################################################################

- name: "Looping through git repositories"
  ansible.builtin.git:
    dest: "{{ item.dest | default(omit) }}"
    recursive: "{{ item.recursive | default(omit) }}"
    remote: "{{ item.remote | default(omit) }}"
    repo: "{{ item.repo | default(omit) }}"
    single_branch: "{{ item.single_branch | default(omit) }}"
  loop: "{{ iac_git_repos | default([]) }}"
  when: iac_git_repos | length > 0
