---
###############################################################################
#
# post_installs_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what variables are configured"
  ansible.builtin.set_fact:
    iac_post_install_jobs: "{{ pg_instance_record.0.post_install.jobs | default([]) }}"
    pg_version: "{{ pg_instance_record.0.version | string }}"
  when: pg_instance_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_post_install_jobs is defined
      - pg_version is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING POST_INSTALLS ARE PRESENT
###############################################################################

- name: "Looping through post_install jobs"
  ansible.builtin.include_tasks: "post_install_present.yml"
  loop: "{{ iac_post_install_jobs }}"
  loop_control:
    loop_var: iac_post_install_job
  when: iac_post_install_jobs | length > 0
