---
###############################################################################
#
# role_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what variables are configured"
  ansible.builtin.set_fact:
    pg_db_role: "{{ pg_role_record.name }}"
  when: pg_role_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - pg_db_role is defined
      - pg_instance is defined
      - pg_port is defined
      - pg_version is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING USER IS ADDED IF IT DOESN'T EXIST
###############################################################################

- name: "Setting variables"
  ansible.builtin.set_fact:
    pg_cli_command: "/usr/pgsql-{{ pg_version }}/bin/psql postgres -p {{ pg_port }} -tXAc \"SELECT 1 FROM pg_roles WHERE rolname='{{ pg_db_role }}'\""

- name: "Checking if user already exists"
  become: true
  become_user: "{{ pg_os_user }}"
  ansible.builtin.command: "{{ pg_cli_command }}"
  changed_when: false
  register: role_exists

- name: "Preparing CREATE ROLE command if user does not exist"
  block:
    - name: "Setting optional attributes for CREATE ROLE"
      ansible.builtin.set_fact:
        pg_db_role_password_str: >-
          {{ "PASSWORD '{{ pg_role_record.password }}'" if (pg_role_record.password is defined) else '' }}
        pg_db_role_encrypted_password_str: >-
          {{ "ENCRYPTED PASSWORD '{{ pg_role_record.encrypted_password }}'" if (pg_role_record.encrypted_password is defined) else '' }}
        pg_db_role_createdb_str: >-
          {{ 'CREATEDB' if (pg_role_record.createdb is defined and pg_role_record.createdb | bool) else 'NOCREATEDB' if pg_role_record.createdb is defined else '' }}
        pg_db_role_createrole_str: >-
          {{ 'CREATEROLE' if (pg_role_record.createrole is defined and pg_role_record.createrole | bool) else 'NOCREATEROLE' if pg_role_record.createrole is defined else '' }}
        pg_db_role_superuser_str: >-
          {{ 'SUPERUSER' if (pg_role_record.superuser is defined and pg_role_record.superuser | bool) else 'NOSUPERUSER' if pg_role_record.superuser is defined else '' }}
        pg_db_role_login_str: >-
          {{ 'LOGIN' if (pg_role_record.login is defined and pg_role_record.login | bool) else 'NOLOGIN' if pg_role_record.login is defined else '' }}
    - name: "Assembling full CREATE ROLE psql command"
      ansible.builtin.set_fact:
        pg_cli_command: >-
          /usr/pgsql-{{ pg_version }}/bin/psql postgres -p {{ pg_port }} -c "CREATE ROLE \"{{ pg_db_role }}\" {{ pg_db_role_password_str }} {{ pg_db_role_encrypted_password_str }} {{ pg_db_role_createdb_str }} {{ pg_db_role_createrole_str }} {{ pg_db_role_superuser_str }} {{ pg_db_role_login_str }}"
  when:
    - role_exists.stdout != '1'

- name: "Preparing ALTER ROLE command if user does exist"
  block:
    - name: "Setting optional attributes for ALTER ROLE"
      ansible.builtin.set_fact:
        pg_db_role_password_str: >-
          {{ "PASSWORD '{{ pg_role_record.password }}'" if (pg_role_record.password is defined) else '' }}
        pg_db_role_encrypted_password_str: >-
          {{ "ENCRYPTED PASSWORD '{{ pg_role_record.encrypted_password }}'" if (pg_role_record.encrypted_password is defined) else '' }}
        pg_db_role_createdb_str: >-
          {{ 'CREATEDB' if (pg_role_record.createdb is defined and pg_role_record.createdb | bool) else 'NOCREATEDB' if pg_role_record.createdb is defined else '' }}
        pg_db_role_createrole_str: >-
          {{ 'CREATEROLE' if (pg_role_record.createrole is defined and pg_role_record.createrole | bool) else 'NOCREATEROLE' if pg_role_record.createrole is defined else '' }}
        pg_db_role_superuser_str: >-
          {{ 'SUPERUSER' if (pg_role_record.superuser is defined and pg_role_record.superuser | bool) else 'NOSUPERUSER' if pg_role_record.superuser is defined else '' }}
        pg_db_role_login_str: >-
          {{ 'LOGIN' if (pg_role_record.login is defined and pg_role_record.login | bool) else 'NOLOGIN' if pg_role_record.login is defined else '' }}
    - name: "Assembling full CREATE ROLE psql command"
      ansible.builtin.set_fact:
        pg_cli_command: >-
          /usr/pgsql-{{ pg_version }}/bin/psql postgres -p {{ pg_port }} -c "ALTER ROLE \"{{ pg_db_role }}\" {{ pg_db_role_password_str }} {{ pg_db_role_encrypted_password_str }} {{ pg_db_role_createdb_str }} {{ pg_db_role_createrole_str }} {{ pg_db_role_superuser_str }} {{ pg_db_role_login_str }}"
  when:
    - role_exists.stdout == '1'

- name: "Ensuring role is present"
  become: true
  become_user: "{{ pg_os_user }}"
  ansible.builtin.command: "{{ pg_cli_command }}"
  register: role_changed
  changed_when: "role_changed.rc == 0"

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Created role {{ pg_version }}/{{ pg_instance }}/{{ pg_db_role }}"

- name: "Looping through in_roles"
  ansible.builtin.include_tasks: "in_role_present.yml"
  loop: "{{ pg_role_record.in_roles }}"
  loop_control:
    loop_var: pg_grant_role
  when:
    - (pg_role_record.in_roles | default([])) | length > 0
